config/routes.rb
Rails.application.routes.draw do

  root :to => 'sessions#new'
  
  get 'sessions/new'

  get 'users/new'
  
  get 'signup'  => 'users#new'
  
  get 'login'   => 'sessions#new'
  
  get 'login/new'
  
  delete 'logout'  => 'sessions#destroy'

  resources :entries
  
  resources :users
  
  resources :sessions

  resources :feeds do
    member do
      get 'retrieve'
      post 'subscribe'
      post 'unsubscribe'
    end
  end

  mount SuperfeedrEngine::Engine => SuperfeedrEngine::Engine.base_path # Use the same to set path in the engine initialization!

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :feed

	validates :atom_id, uniqueness: {scope: :feed_id}

	default_scope {
		order('created_at DESC')
	}
end

app/models/feed.rb
require 'digest/md5'

class Feed < ActiveRecord::Base

  has_many :entries, dependent: :destroy

  validates_presence_of :title, :message => "obrigatorio."
  
  validates_presence_of :url, :message => "obrigatoria."

  def secret
		Digest::MD5.hexdigest(created_at.to_s)
  end

  def notified params
    update_attributes(:status => params["status"]["http"])

  	params['items'].each do |i|
  		entries.create(:atom_id => i["id"], :title => i["title"], :url => i["permalinkUrl"], :content => i["content"])
  	end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
 
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :destroy]

  def index
    if logged_in?
      @entries = Entry.all
    else
        redirect_to root_url
    end
  end

  def show
  end

  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Noticia excluida com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    def set_entry
      @entry = Entry.find(params[:id])
    end

    def entry_params
      params.require(:entry).permit(:feed_id, :atom_id, :title, :url, :content)
    end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy, :retrieve]

  def index
    @feeds = Feed.all
  end

  def show
  end

  def new
    @feed = Feed.new
  end

  def edit
  end

  def retrieve
    body, ok = SuperfeedrEngine::Engine.retrieve(@feed)
    if !ok
      redirect_to @feed , notice: body
    else
      @feed.notified JSON.parse(body)
      redirect_to @feed , notice: "Feed atualizado com sucesso!"
    end
  end

  def create
    @feed = Feed.new(feed_params)
    
    existeFeed = Feed.find_by(url: @feed.url, user_id: @feed.user_id )
    
    if existeFeed.nil?
      if @feed.save
        body, ok = SuperfeedrEngine::Engine.subscribe(@feed, {:retrieve => true})
        if !ok
          redirect_to @feed, notice: "Feed cadastrado com sucesso, mas nao carregado. #{body}"
        else
          if body
            @feed.notified JSON.parse(body)
          end
          redirect_to @feed, notice: 'Feed cadastrado e carregado com sucesso!'
        end
      else
        render :new
      end
    else
      redirect_to '/feeds/new', notice: 'Feed ja cadastrado para este usuario!'
    end
    
  rescue => e
    @feed.destroy

    redirect_to '/feeds/new', notice: "Nao foi possivel realizar sua solicitacao, verifique se a URL eh valida (Ex: http://www...)"

  end

    def update
      
    id = @feed.id
    existeFeed = Feed.find_by(url: :url, user_id: :user_id )

    if existeFeed.nil?
      if @feed.update(feed_params)
        body, ok = SuperfeedrEngine::Engine.unsubscribe(@feed)
        if !ok
          render :edit, notice: "Feed alterado com sucesso, mas nao foi possivel recarrega-lo. #{body}"
        else
          body, ok = SuperfeedrEngine::Engine.subscribe(@feed)
          if !ok
            render :edit, notice: "Feed alterado com sucesso, mas nao foi possivel recarrega-lo. #{body}"
          else
            redirect_to @feed, notice: 'Feed alterado com sucesso!'
          end
        end
      else
        render :edit
      end
      
    else
      url = "/feeds/" + existeFeed.id.to_s + "/edit"
      redirect_to url , notice: "Feed ja cadastrado para esse usuario."
    end  
  
    rescue => e
      url = "/feeds/" + id.to_s + "/edit"
      redirect_to url , notice: "Nao foi possivel realizar sua solicitacao, verifique se a URL eh valida (Ex: http://www...)"
    
  end

  def destroy
    body, ok =  SuperfeedrEngine::Engine.unsubscribe(@feed)
    if !ok
      redirect_to @feed, notice: body
    else
      @feed.destroy
      redirect_to feeds_url, notice: 'Feed excluido com sucesso!'
    end
    
    rescue => e
    @feed.destroy
    redirect_to feeds_url, notice: 'Feed excluido com sucesso!'
  end

  private
    def set_feed
      @feed = Feed.find(params[:id])
    end

    def feed_params
      params.require(:feed).permit(:title, :url, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if logged_in?
      redirect_to entries_path
    end
  end

  def create
    
    user = User.find_by(email: params[:session][:email].downcase, password: params[:session][:password])
   
    if user.nil?
      redirect_to '/login', notice: 'Login e/ou senha incorreto(s)!'
    else
      log_in user
      redirect_to entries_path
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :retrieve]
   
  def show
    @user = User.find(params[:id])
  end
  
  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end
  
  def create
    
   
    @user = User.new(user_params)
    
    if @user.name.delete(' ') == '' or @user.password.delete(' ') == '' or @user.email.delete(' ') == ''
        redirect_to '/signup', notice: 'Favor preencher todos os campos!'
    else
      existeUser = User.find_by_email(@user.email)
     
      if existeUser.nil?
          if @user.save
           flash[:success] = "Bem-vindo ao MyReader!"
           redirect_to @user
          else
            render 'new'
          end
      else   
        redirect_to '/signup', notice: 'Email ja cadastrado!'
      end
    end
  end
  
  # PATCH/PUT /feeds/1
  def update
     @user = User.find(params[:id])
     @user.update(user_params)
   redirect_to @user
  end
  
  # DELETE /feeds/1
  def destroy
    
      @user.destroy
      redirect_to @user
      
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    puts 'log out inicio'
    session.delete(:user_id)
    @current_user = nil
    puts 'log out fim'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_index.html.erb
<table class="table table-striped" id="table">
  <thead>
    <tr>
      <th>T&iacute;tulo</th>
      <th>Not&iacute;cia</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% entries.each do |entry| %>
      <% if current_user.id == entry.feed.user_id %>
        <tr>
          <td><strong><a class='text-danger' href='../feeds/<%= entry.feed.id %>'><i class='fa fa-rss-square'></i> <%= entry.feed.title %></a></strong></td>
          <td><a class='text-warning' href='<%= entry.url %>' target='_blank'><%= entry.title %></a></td>
          <td><%= link_to 'Excluir', entry, method: :delete, data: { confirm: 'Deseja realmente excluir?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/entries/index.html.erb
<h4 id="notice" class='text-center text-success'><strong><%= notice %></strong></h4>

<div class='text-right'>
    Usuario: <strong><%= current_user.name %></strong> <%= link_to " SAIR", logout_path, method: "delete", class: "btn btn-default glyphicon glyphicon-log-out red" %>
    </div>
<hr />
<p class='text-right'>
    <a class='btn btn-danger' href='feeds'><i class="fa fa-rss"></i> Meus Feeds</a> 
    <a class='btn btn-warning' href='feeds/new'><i class="fa fa-plus"></i> Adicionar Feed</a></p>    

<% if logged_in? %>

    <%= render :partial => 'index', :locals => {:entries => @entries} %>

<% else %>
    <p>Entre no MyReader para visualizar seus feeds de noticias!</p>
<% end %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Feed:</strong>
  <%= @entry.feed_id %>
</p>

<p>
  <strong>Atom:</strong>
  <%= @entry.atom_id %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @entry.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @entry.url %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= @entry.content %>
</p>

<%= link_to 'Editar', edit_entry_path(@entry) %> |
<%= link_to 'Voltar', entries_path %>

app/views/feeds/_form.html.erb
			<div class="row">
				<div class="col-lg-6">
				</div>
				<div class="col-lg-6">
				  <p class='text-right'>
    <%= link_to "Sair", logout_path, method: "delete", class: 'btn btn-default' %></p>
				</div>
			</div>


<h5 id="notice" class='text-warning'><strong><%= notice %></strong></h5>
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      
<div class='alert alert-danger alert-dismissible' role='alert'>
  <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
  <h4><strong><%= pluralize(@feed.errors.count, 'erro') %>, favor corrigir:</strong></h4>
      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>  
</div>      
    </div>
  <% end %>

			<div class="row">
				<div class="col-lg-2">
				</div>
				<div class="col-lg-8">
  <div class="field">
    <label for="feed_titulo">T&iacute;tulo</label><br />
    <%= f.text_field :title, class: 'form-control' %>
  </div><br />
  <div class="field">
    <label for="feed_url">Url</label><br />
    <%= f.text_field :url, class: 'form-control' %>
  </div>
  <div class="field">
    <input type="hidden" name="feed[user_id]" id="feed_user_id" value="<%= current_user.id %>">
  </div>
  <div class="actions">
    <br /><p class="text-center"><input type="submit" name="commit" value="Cadastrar" class='btn btn-danger' /> <a class='btn btn-default' href='..'>Cancelar</a></p>
  </div>
<% end %>
				</div>
				<div class="col-lg-2">
				</div>
      </div>				

app/views/feeds/edit.html.erb
<h3 class='text-warning'>> Editar Feed</h3>
<div class='text-right'>
    Usuario: <strong><%= current_user.name %></strong> <%= link_to " SAIR", logout_path, method: "delete", class: 'btn btn-default glyphicon glyphicon-log-out red' %>
    </div>
<hr />

<%= render 'form' %>

<br />

app/views/feeds/index.html.erb
<h4 id="notice" class='text-center text-success'><strong><%= notice %></strong></h4>

<h3 class='text-danger'>> Meus Feeds</h3>
<div class='text-right'>
    Usuario: <strong><%= current_user.name %> <%= link_to " SAIR", logout_path, method: "delete", class: 'btn btn-default glyphicon glyphicon-log-out red' %>
    </div>
<hr />

			<div class="row">
				<div class="col-md-6">
				  <p class='text-left'><a class='btn btn-danger' href='..'><i class="fa fa-home"></i> In&iacute;cio</a></p>
				</div>
				<div class="col-md-6">
				  <p class='text-right'><a class='btn btn-warning' href='../feeds/new'><i class="fa fa-plus"></i> Adicionar Feed</a></p>
				</div>
			</div>


 

<table class="table table-striped">
  <thead>
    <tr>
      <th>T&iacute;tulo</th>
      <th>Url</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  

  <tbody>
    <% @feeds.each do |feed| %>
    <% if current_user.id == feed.user_id %>
      <tr>
        <td><strong><i class="fa fa-rss-square"></i> <%= feed.title %></strong></td>
        <td><i class="fa fa-globe"></i> <%= feed.url %></td>
        <td><%= link_to 'Atualizar', retrieve_feed_path(feed) %></td>
        <td><%= link_to 'Exibir', feed %></td>
        <td><%= link_to 'Editar', edit_feed_path(feed) %></td>
        <td><%= link_to 'Excluir', feed, method: :delete, data: { confirm: 'Deseja realmente excluir?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br />

app/views/feeds/new.html.erb
<h3 class='text-warning'>> Adicionar Feed</h3>

<div class='text-right'>
Usuario: <strong><%= current_user.name %></strong> <%= link_to " SAIR", logout_path, method: "delete", class: 'btn btn-default glyphicon glyphicon-log-out red' %>
    </div>
<hr />


<% if logged_in? %>

    <%= render 'form' %>
    
<% else %>
    Você precisa entrar no MyReader para adicionar um novo feed!

<% end %>

<br />

app/views/feeds/show.html.erb
<h4 id="notice" class='text-center text-success'><strong><%= notice %></strong></h4>

<h3 class='text-danger'>> Detalhes do Feed <%= @feed.id %></h3>
<div class='text-right'>
    Usuario: <strong><%= current_user.name %></strong> <%= link_to " SAIR", logout_path, method: "delete", class: 'btn btn-default glyphicon glyphicon-log-out red' %>
    </div>
<hr />
<div class="well">

<p>
  <strong>T&iacute;tulo:</strong>
  <%= @feed.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Criado:</strong>
  <%= @feed.created_at %>
</p>

<p>
  <strong>Atualizado:</strong>
  <%= @feed.updated_at %>
</p>

</div>

			<div class="row">
				<div class="col-lg-6">
				  <p class='text-left'><a class='btn btn-danger' href='..'><i class="fa fa-home"></i> In&iacute;cio</a></p>
				</div>
				<div class="col-lg-6">
				  <p class='text-right'><a class='btn btn-default' href='../feeds/<%= @feed.id %>/retrieve'><i class="fa fa-refresh"></i> Atualizar</a>
				  <a class='btn btn-warning' href='../feeds/<%= @feed.id %>/edit'><i class="fa fa-edit"></i> Editar</a>
				  <a class='btn btn-danger' href='../feeds'><i class="fa fa-rss"></i> Meus Feeds</a></p>
				</div>
			</div>

<%= render :partial => 'entries/index', :locals => {:entries =>  @feed.entries} %>

<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MyReader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="text/css" href="/assets/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="/assets/dataTables.bootstrap.css">
  <link rel="stylesheet" type="text/css" href="/assets/style.css">
  <script type="text/javascript" language="javascript" src="/assets/jquery-1.10.2.min.js"></script>
  <script type="text/javascript" language="javascript" src="/assets/jquery.dataTables.min.js"></script>
  <script type="text/javascript" language="javascript" src="/assets/dataTables.bootstrap.js"></script>    
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/assets/favicon.png">
</head>
<body>

<p class='text-right'>
	<a href='http://webserver.cin.ufpe.br/~smc2/myreader/manual' target="_blank" title="Manual" class="red">
<span class="fa-stack fa-lg">
  <i class="fa fa-circle fa-stack-2x"></i>
  <i class="fa fa-book fa-stack-1x fa-inverse"></i>
</span></a>
</p>

<div class="container">
	<div class="row">
		<div class="col-lg-12">

<p class='text-center'><a href='..'><img src="/assets/logo.png" alt="MyReader" title='MyReader' /></a></p>

<h4 class='text-center text-warning'><i class="fa fa-leanpub"></i> Leitor de feed de not&iacute;cias no formato RSS. Um "substituto" ao Google Reader.</h4>

<hr />

<%= yield %>

<hr />

<p class='text-center'><small class='text-muted'><strong>My<i class="fa fa-rss fa-2x"></i>Reader</strong> - Projetado por: Iuri | Marcelo Cicco | Marcelo Gomes | Menino | Rivaldo | Sandro</small></p>

		</div>
	</div>
</div>

	<script type="text/javascript" class="init">
		$(document).ready(function() {
			$('#table').dataTable( {
				language: {
				"sEmptyTable": "Nenhum registro encontrado",
				"sInfo": "Mostrando de _START_ ate _END_ de _TOTAL_ registros",
				"sInfoEmpty": "Mostrando 0 ate 0 de 0 registros",
				"sInfoFiltered": "(Filtrados de _MAX_ registros)",
				"sInfoPostFix": "",
				"sInfoThousands": ".",
				"sLengthMenu": "_MENU_ Resultados por pagina",
				"sLoadingRecords": "Carregando...",
				"sProcessing": "Processando...",
				"sZeroRecords": "<p class='text-center text-danger'><strong>Nenhum registro encontrado!</strong></p>",
				"sSearch": "Pesquisar ",
				"oPaginate": {
					"sNext": "Proximo",
					"sPrevious": "Anterior",
					"sFirst": "Primeiro",
					"sLast": "Ultimo"
					},
				"oAria": {
					"sSortAscending": ": Ordenar colunas de forma ascendente",
					"sSortDescending": ": Ordenar colunas de forma descendente"
					}
				}, 		
					"pageLength": 10
			});
		});
	</script>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |u| %>

  <div class="field">
    <%= u.text_field :name %>
  </div>
  <div class="field">
    <%= u.text_field :email %>
  </div>
  <div class="actions">
    <%= u.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
<%= link_to 'Home', entries_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', signup_path %>
<%= link_to 'Home', entries_path %>

app/views/users/new.html.erb
		<div class="col-lg-3 column">
		</div>
		<div class="col-lg-6 column"><br />
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h3 class="panel-title">
						<span class="glyphicon glyphicon-edit"></span> <strong>Cadastro</strong>
					</h3>
				</div>
				<div class="panel-body">
			<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			  <h5 id="notice" class='text-center text-warning'><strong><%= notice %></strong></h5>
				<div class="form-group ">
					 <label for="inputSenha">Nome</label>
					 <div class="input-group">
					 <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
					 <%= f.text_field :name, class: 'form-control' %>
					 </div>
				</div>			  
				<div class="form-group ">
					 <%= f.label :email %>
					 <div class="input-group">
					 <div class="input-group-addon"><i class="fa fa-at"></i></div>
					 <%= f.email_field :email, class: 'form-control' %>
					 </div>
				</div>
				<div class="form-group ">
					 <label for="inputSenha">Senha</label>
					 <div class="input-group">
					 <div class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></div>
					 <%= f.password_field :password, class: 'form-control' %>
					 </div>
				</div>
				<p class="text-center"><%= f.submit "Criar minha conta :)", class: "btn btn-danger" %> <a class='btn btn-default' href='../login'>Cancelar</a></p>
			<% end %>
				</div>
				<div class="panel-footer">
				</div>
				</div>
		</div>
		<div class="col-lg-3 column">
		</div>

<div class="row">
</div>

app/views/users/show.html.erb
<div class="well">
<h4 class="text-center text-danger"><i class="fa fa-3x fa-smile-o"></i><br />Bem-vindo ao <strong>MyReader</strong> <%= @user.name %>,
você se cadastrou com o email: <%= @user.email %></h4>
<h4 class="text-center">Clique em uma opção para continuar:</h4><br />
<p class='text-center'><a class='btn btn-lg btn-danger' href='..'><i class="fa fa-home"></i> Início</a>
<a class='btn btn-lg btn-warning' href='http://webserver.cin.ufpe.br/~smc2/myreader/manual' target="_blank"><i class="fa fa-book"></i> Manual</a>
<%= link_to " SAIR", logout_path, method: "delete", class: 'btn btn-lg btn-default glyphicon glyphicon-log-out red' %></p>
</div>